### ISSUE TITLE
documentation about feature list

### ISSUE THREAD

**Issue by mstrYoda** [Rolix44/Kubestroyer#8]
WDYT about listing currently supported attacks/vulnerability checks on the readme file?

So people can create issue/PR about missing parts.

**Comment by Rolix44** [comment]
That could be a great idea !  I can add it in a new section before the roadmap

**Comment by Rolix44** [comment]
The section as been added to the readme file and list all features available with the tool. Thanks for the idea and contribution :wink:
Feel free to open new PR/issue if you have other ideas !
